### ISSUE TITLE
Build my own nodejs jupyter

### ISSUE THREAD

**Issue by frank-zsy** [poad/docker-jupyter#34]
Hello, thanks for the Docker images you offered and I really appreciate, it makes me very easy to get my hands on jupyter.

But I need more local libraries installed in the environment to support my server side render needs.

And I cloned your repo and add the libraries I need into the Dockerfile and build the image again, the images built correctly but when I start the image I can't find `node.js` kernel in the notebook. Is there something I missed here?

**Comment by frank-zsy** [comment]
And I also tried `Plotly` from `ijavascript-plotly`, the image can not render in the browser but can be rendered in VSCode, I am not sure what I got wrong here, could you help me please.

**Comment by poad** [comment]
@frank-zsy 

Hello.
Thank you very much for using the image I made.

In the poad/docker-jupyter:nodejs image, Node.js has been installed.

The kernel has been installed with root user privileges.
Run `npm -g i ijavascript-plotly` in the `RUN` command of https://github.com/poad/docker-jupyter/blob/main/nodejs/Dockerfile#L100-L103.

Since you are using JupyterLabs, try `jupyter labextension install jupyterlab-plotly @jupyter-widgets/jupyterlab-manager plotlywidget`.

**Comment by frank-zsy** [comment]
@poad Thanks for you reply. Actually I add some underlying libs like `librsvg2-dev`, `libgif-dev` to enable server render by `echarts` and `canvas`.

And I tried `plotly` with your guide and all works like a charm, the charts can be rendered right in the lab. But still there is no `node.js` kernel with my own build imag, is there any config to enable the kernel or something I may missed?

**Comment by poad** [comment]
@frank-zsy
I've just noticed and fixed this, but it seems that the image on Docker Hub is still outdated.

The old image is based on Alpine Linux, but it seems to be missing the Shared Object needed to run Node.js.

If you are using a Dockerfile from the Alpine Linux base, you may want to add `libc6-compat musl` to the apk add file.

**Comment by poad** [comment]
@frank-zsy 
The new Dockerfile was missing the Node.js (IJavascript) Kernel installation process.

This is being fixed now.

**Comment by poad** [comment]
@frank-zsy 
Fixed at https://github.com/poad/docker-jupyter/commit/2a1c28ed108a12f2a16527d5e4a98a0c0e09517e.

Docker Image sha `95968ff92d826eca086a85a4157e9afddc66866022a4282dcc93189d9702129e`.

**Comment by frank-zsy** [comment]
Great! Thanks for your help and now everything works fine with plotly. Thanks you very much.
